---
- name: "Bootstrap Ansible Playbook Files"
  hosts: "all"
  gather_facts: true
  remote_user: root
  strategy: free
  become: true
  become_user: root

  tasks:

    - name: "Include tool.bootstrap_playbook"
      tags:
        - "tool.bootstrap_playbook"
      vars:
        input_bootstrap_playbook_user: "{{ input_bootstrap_playbook_user }}"
        input_bootstrap_playbook_base_path: "{{ input_bootstrap_playbook_base_path }}"
        input_bootstrap_playbook_meta_author: "{{ input_bootstrap_playbook_meta_author }}"
        input_bootstrap_playbook_meta_namespace: "{{ input_bootstrap_playbook_meta_namespace }}"
        input_bootstrap_playbook_meta_playbook_name: "{{ input_bootstrap_playbook_meta_playbook_name }}"
        input_bootstrap_playbook_meta_playbook_name: "{{ input_bootstrap_playbook_meta_playbook_name }}"
        input_bootstrap_playbook_meta_description: "{{ input_bootstrap_playbook_meta_description }}"
        input_bootstrap_playbook_meta_company: "{{ input_bootstrap_playbook_meta_company }}"
        input_bootstrap_playbook_tags: "{{ input_bootstrap_playbook_tags }}"
      ansible.builtin.include_role:
        name: "tool.bootstrap_playbook"
