---
- name: "Bootstrap Ansible Playbook Files"
  hosts: "all"
  gather_facts: true
  remote_user: root
  strategy: free
  become: true
  become_user: root

  tasks:

    - name: "Include tool.bootstrap_playbook"
      tags:
        - "tool.bootstrap_playbook"
      vars:
        bootstrap_playbook_base_path: "{{ input_bootstrap_playbook_base_path }}"
        bootstrap_playbook_meta_playbook_name: "{{ input_bootstrap_playbook_meta_playbook_name }}"
        bootstrap_playbook_meta_namespace: "{{ input_bootstrap_playbook_meta_namespace }}"
        bootstrap_playbook_technologies: "{{ input_bootstrap_playbook_technologies }}"
        bootstrap_playbook_meta_company: "{{ input_bootstrap_playbook_meta_company }}"
      ansible.builtin.include_role:
        name: "tool.bootstrap_playbook"
